### ISSUE TITLE
Manuel utilisateur

### ISSUE THREAD

**Issue by Nono98** [gen-classroom/projet-dgpw#114]
_Rédigez un manuel utilisateur reproductible qui guide l’utilisateur lors de la création d’un site statique avec votre
générateur_

**Comment by CassandreWoj** [comment]
- [ ] Relire le document existant (README.md)
- [ ] Compléter la marche à suivre à la fin du sprint
- [ ] Essayer de suivre le step-by-step
- [ ] Rédiger les points manquants
