### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by Nono98** [gen-classroom/projet-dgpw#117]
_Configurez LGTM6 , SonarQube7 ou un outil équivalent pour détecter des bugs et des vulnérabilités dans votre code.
Expliquez en quoi l’un de ces outils vous aura permis d’améliorer vos pratiques de développement._

**Comment by CassandreWoj** [comment]
- [ ] Discuter des différents outils existants 
- [ ] Choisir un outil
- [ ] Documenter le choix dans le rapport

1. https://lgtm.com/help/lgtm/getting-started (LGTM)
2. https://www.sonarqube.org/ (SONARQUBE)
3. https://www.perforce.com/products/klocwork (KLOCWORK)
