### ISSUE TITLE
Code benchmarking

### ISSUE THREAD

**Issue by Nono98** [gen-classroom/projet-dgpw#118]
_Utilisez JMH pour mesurer les performances de votre compilateur markdown ou de votre moteur de rendu. Utilisez
VisualVM pour profiler une exécution de la commande build. Incluez ces données dans votre rapport et discutez
d’une éventuelle optimisation (sans nécessairement l’implémenter)._

**Comment by CassandreWoj** [comment]
JMH step-by-step : https://www.baeldung.com/java-microbenchmark-harness
VisualVM : https://visualvm.github.io/

- [ ] Inclure JMH dans le projet
- [ ] Mesurer les performances du compilateur md ou du moteur de templates
- [ ] Inclure VisualVM dans le projet
- [ ] Profiler une exécution de build
- [ ] Ajouter les données dans le rapport
- [ ] Discuter les données
- [ ] Discuter les améliorations possibles

**Comment by CassandreWoj** [comment]
https://www.javacodegeeks.com/2016/12/adding-microbenchmarking-build-process.html
https://mkyong.com/java/java-jmh-benchmark-tutorial/

**Comment by CassandreWoj** [comment]
![image](https://user-images.githubusercontent.com/49147626/120653964-7d7b7400-c481-11eb-848c-8ce35d17d950.png)

Performance du compilateur (commande `buid`).
