### ISSUE TITLE
Créer un moteur de template

### ISSUE THREAD

**Issue by dosseggegw1** [gen-classroom/projet-dgpw#97]
A découper en sous-partie

**Comment by dosseggegw1** [comment]
<dependency>
   <groupId>com.github.jknack</groupId>
   <artifactId>handlebars-maven-plugin</artifactId>
   <version>4.2.0</version>
</dependency>

**Comment by CassandreWoj** [comment]
Modifier la commande "build" : 

- [ ] injecter la propriété titre du fichier config.yaml dans la variable {{ site.titre }}
- [ ] injecter la propriété titre du fichier page.md dans la variable {{ page.titre }}
- [ ] inclure le fichier menu.html dans la page
- [ ] injecter le HTML produit par la compilation du fichier markdown page.md dans la variable {{ content }}

**Comment by CassandreWoj** [comment]
Tutoriel de référence : https://www.baeldung.com/handlebars

**Comment by CassandreWoj** [comment]
Temps passé le 03.05 : 3h15

**Comment by CassandreWoj** [comment]
Temps passé le 07.05 : 3h30
