### ISSUE TITLE
Automatiser les release - Continuous delivery

### ISSUE THREAD

**Issue by dosseggegw1** [gen-classroom/projet-dgpw#99]
En tant que développeur, j’aimerai que la création et la publication d’une nouvelle release soit automatisée à l’aide de GitHub actions. En d’autres termes, j’aimerai que le fichier jar ou le fichier zip de la release soit publié de manière automatique lorsqu’un tag correspondant à une version (p.ex. v0.0.2) est publié sur git.

**Comment by CassandreWoj** [comment]
https://github.com/marketplace/actions/automatic-releases
